import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from './layout/NavBar'
import HeroBanner from './elements/HeroBanner'
import SubNav from './layout/SubNav'
import ReviewerGrid from './layout/ReviewerGrid'

function Layout() {
  return (
    <div className=''>
      <Head>
        <title>iReviewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/iReviewer-Logo-Small.svg" />
      </Head> 
      <NavBar/>
      <HeroBanner/>
      <SubNav/>
    </div>
  )
}

export default Layout
