import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import HeroBanner from '../components/HeroBanner'
import ReviewerCard from '../components/ReviewerCard'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout/>
      <ReviewerCard/>
    </div>
  )
}

export default Home
